### ISSUE TITLE
parser ERROR for tracr.py 

### ISSUE THREAD

**Issue by HGeerlings** [csm-adapt/tracr#2]
Trying to run:

`./tracr -h`

to see if help features are working. There seems to be an error:

`wl-dhcp-229-55:delme henrygeerlings$ ./tracr -h` 
`ERROR, UNEXPECTED EXCEPTION`
`dest supplied twice for positional argument`
`Traceback (most recent call last):`
  `File "./tracr", line 160, in <module>`
   `help='Files to process.')`
 `File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1275, in add_argument`
    `raise ValueError('dest supplied twice for positional argument')`
`ValueError: dest supplied twice for positional argument`

Unfamiliar with setting up positional arguments, any tips here?

Thanks, 
HG

**Comment by bkappes** [comment]
It should work now.

Branden

**Comment by HGeerlings** [comment]
Fantastic, ./tracr -h running now, will close issue.
