### ISSUE TITLE
Possible typo in tracr.py for thresholding

### ISSUE THREAD

**Issue by HGeerlings** [csm-adapt/tracr#3]
Noticed the following on line 63 of tracr.py:

`arr = (arr > args.threshold)`

This will binarize the data in such a way that the air is False and the sample is True, which may be problematic since the feature detection uses an np.ones(...) structure. Just want to get a second opinion before changing to make sure I'm not missing something here. 

Thanks.

**Comment by bkappes** [comment]
This won’t be a problem. In fact, it is “more” accurate, but only in a very esoteric way; in python and in C, 0 is False while anything non-zero is True. If you cast a boolean to an int (float, double, etc.), the resulting value is 1 — so False == 0 and True == 1.

The reason I prefer to use the mask,

mask = (arr > args.threshold)

is that this explicitly tells anyone reading the code what is True and what is False. What if arr[i,j] = 1.234e-16? While that would evaluate to True, isn’t this really just 0 + floating point rounding error? It’s a very hard bug to track down, so I explicitly use the mask.

Branden

**Comment by HGeerlings** [comment]
Branden, 

Thanks for the insights. So we should avoid using:

‘arr = (arr<threshold)’

instead? 

## 

Henry

**Comment by bkappes** [comment]
No, use

arr = (arr < threshold)

I substituted “mask” in the earlier email to make clear it’s function.

arr = (arr < threshold)

indicates that arr should always have been a boolean array, but python, as a weakly typed language, could not ensure that.

Branden
